
import { getServerSession } from 'next-auth'
import NavBar from '../components/NavBar'
import { options } from '../api/auth/[...nextauth]/options'
import SideBar from '../components/SideBar'
import { redirect } from 'next/navigation'

export const metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const session = await getServerSession(options)
    if (!session) {
        redirect('/login')
    }
    return (<>
        <NavBar user={session?.user} />
        <div className='flex'>
            <div className='w-[300px] h-[calc(100vh-56px)] hidden sm:block'>
                <SideBar />
            </div>
            <div className='w-full h-[calc(100vh-56px)] overflow-y-auto '>
                
                {children}
            </div>
        </div>


    </>
    )
}
